### ISSUE TITLE
Unescaped characters error

### ISSUE THREAD

**Issue by marcoscaceres** [timaschew/link-checker#2]
Give, for instance:

```HTML
      <p>
        The working group maintains <a href=
        "https://github.com/w3c/payment-method-basic-card/issues?utf8=%E2%9C%93&amp;q=is%3Aopen%20is%3Aissue%20-label%3A%22Priority%3A%20Postponed%22%20">
        a list of all bug reports that the group has not yet addressed</a>.
        Pull requests with proposed specification text for outstanding issues
        are strongly encouraged.
      </p>
```

The link link checker throws: 

> could not fetch external page: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters from output.html to https://github.com/w3c/payment-method-basic-card/issues?utf8=✓&q=is:open is:issue -label:"Priority: Postponed" 

I'm guessing, as the error states, that the URL needs to be encoded before being sent?

**Comment by timaschew** [comment]
Sorry for the delay.
URLs were decoded in order to fix some anchors in scaladoc.
Now only anchors are decoded and only in javadoc mode.

BTW: I was not able to reproduce the error message:

> ERR_UNESCAPED_CHARACTERS

Where did you got it from?

**Comment by marcoscaceres** [comment]
I can't recall :( I think it just occurred when I ran this from the command line. Thanks regardless for fixing this.
