### ISSUE TITLE
feature_request(paths): support pretty local URLs without .html extension

### ISSUE THREAD

**Issue by Kristinita** [timaschew/link-checker#4]
### 1. Summary

It would be nice, if link-checker will support local paths without `.html` extension. I can't normally use link-checker for internal links without this feature.

### 2. Argumentation

In my [**localhost**](https://github.com/BrowserSync/browser-sync/issues/1055#issuecomment-224293199) and remote server `.html` extension not required; internal links without `.html` successful works. I don't want use `.html` in internal links, it extra data.

### 3. Data

For example, I have `KiraFirstArticle.html` and `KiraSecondArticle.html` files in single folder. `KiraSecondArticle.html` contain valid anchor `#KiraExampleAnchor`.

### 4. Steps to reproduce

```text
link-checker "path/to/my/folder" --disable-external
```

### 5. Expected behavior

**If** in `KiraFirstArticle.html`:

+ `<a href="KiraSecondArticle.html">Kira</a>`
+ `<a href="KiraSecondArticle.html#KiraExampleAnchor">Kira</a>`

link-checker will show, that no errors.

### 6. Non-expected behavior

**Else** in `KiraFirstArticle.html` links as in my real HTML files:

+ `<a href="KiraSecondArticle">Kira</a>`
+ `<a href="KiraSecondArticle#KiraExampleAnchor">Kira</a>`

link-checker show errors:

```text
page not found from KiraFirstArticle.html to KiraSecondArticle
page not found from KiraFirstArticle.html to KiraSecondArticle#KiraExampleAnchor
```

Thanks.

**Comment by timaschew** [comment]
This should already work

**Comment by Kristinita** [comment]
**Status: Not fixed for me :x:**

### 1. Additional data

Maybe I unclearly explained something.

+ `KiraFirstArticle.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KiraFirstArticle</title>
</head>
<body>
    <a href="KiraSecondArticle">Kira</a>
    <a href="KiraSecondArticle#KiraExampleAnchor">Kira</a>
</body>
</html>

```

+ `KiraSecondArticle.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KiraSecondArticle</title>
</head>
<body>
    <p><a id="KiraExampleAnchor"></a></p>
    <h1>Kira Example Anchor</h1>
</body>
</html>

```

I still got errors:

```js
page not found from KiraFirstArticle.html to KiraSecondArticle
anchor not found from KiraFirstArticle.html to KiraSecondArticle#KiraExampleAnchor

2 files were scanned in D:\Kristinita\output\KiraLinkChecker
2 local links and 0 parent links and 0 remote links were checked
2 errors and 0 warnings
```

### 2. Environment

+ Windows 10 Enterprise LTSB 64-bit EN
+ Node.js 12.10.0
+ link-checker 1.3.0

Thanks.

**Comment by timaschew** [comment]
Oh, I was thinking the file names have also no extension.

I'm not sure about this feature. It sound a bit too magic to automatically add the `.html` extension. If we implement it, it needs to be flexible, there could be other extensions as well.
