### ISSUE TITLE
feature_request(paths): encoded URLs support

### ISSUE THREAD

**Issue by Kristinita** [timaschew/link-checker#5]
### 1. Summary

It would be nice, if link-checker will support internal links with encoded anchors like `<a href="#%D0%9A%D0%B8%D1%80%D0%B0">Kira link</a>`.

### 2. Argumentation

Some HTML rendering tools, including the ones I use, may encode non-ASCII symbols in URLs. It would be nice, if link-checker will support their behavior.

[**HTML Tidy**](http://www.html-tidy.org/) — [**the granddaddy of HTML tools, with support for modern standards**](https://github.com/htacg/tidy-html5) — check, that non-encoded anchors is not valid; result for example HTML below:

```text
line 8 column 9 - Warning: <a> escaping malformed URI reference
```

### 3. Data

My example `KiraEncodedURL.html` file:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kira encoded URL test file</title>
</head>
<body>
    <a href="#Кира">“Кира”</a>
    <a href="#%D0%9A%D0%B8%D1%80%D0%B0">“Кира” encoded</a>
    <p><a id="Кира"></a></p>
    <h1>Кира</h1>
</body>
</html>

```

### 4. Steps to reproduce

```text
link-checker "path/to/my/HTML" --disable-external
```

### 5. Expected behavior

No errors or warnings.

### 6. Actual behavior

```text
anchor not found from KiraEncodedURL.html to KiraEncodedURL.html#%D0%9A%D0%B8%D1%80%D0%B0

1 files were scanned in path/to/my/HTML
2 local links and 0 parent links and 0 remote links were checked
1 errors and 0 warnings
```

Thanks.

**Comment by timaschew** [comment]
Sorry for the late response.

**Comment by Kristinita** [comment]
**Status: Fixed for me ✔️**

Thanks!
