### ISSUE TITLE
Issues with --url-ignore on Windows

### ISSUE THREAD

**Issue by oberek** [timaschew/link-checker#6]
It seems to work on Macs, but not on Windows. Additional logging below-

link-checker dist/index.html --allow-hash-href --url-ignore 'https://TEST.com/'

error [Arguments] { '0': 'dist/index.html', '1': [Function], '2': [AsyncFunction] }

0 files were scanned in dist/index.html
0 local links and 0 parent links and 0 remote links were checked
0 errors and 0 warnings
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn link-checker ENOENT
    at notFoundError

**Comment by timaschew** [comment]
I've followed this advice: https://stackoverflow.com/a/10398567
It should be fixed now. Please reopen if not.
